apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "chart.fullname" . }}-cassandra-vss
spec:
  mount: {{ .Values.configphpSecret.vaultMount }}
  path: {{ .Values.configphpSecret.vaultStaticSecretPath }}
  vaultAuthRef: {{ .Values.configphpSecret.vaultAuthRef }}
  type: kv-v2
  destination: 
    create: true
    name: {{ include "chart.fullname" . }}-cassandra-secret
