{{- if .Values.testrail.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "chart.fullname" . }}-ingress
  labels:
    app: testrail
  {{- include "chart.labels" . | nindent 4 }}
  annotations: {{- toYaml .Values.testrail.ingress.annotations | nindent 4 }}
spec:
{{- if .Values.testrail.ingress.ingressClassName }}
  ingressClassName: {{ .Values.testrail.ingress.ingressClassName | quote }}
{{ end }}
{{- if .Values.testrail.ingress.tls }}
  tls:
  - hosts:
    - {{ .Values.testrail.ingress.host }}
{{- if .Values.testrail.ingress.secretName }}
    secretName: {{ .Values.testrail.ingress.secretName }}
{{- end }}
{{- end }}
  rules:
  - host: {{ .Values.testrail.ingress.host }}
    http:
      paths:
      - path: {{ .Values.testrail.ingress.path }}
        pathType: Prefix
        backend:
          service:
            name: {{ include "chart.fullname" . }}-svc
            port:
              number: 8000
{{ end }}
